// triptoo-backend/models/User.js
const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  // _id is automatically generated by MongoDB, no need to define here explicitly
  firebaseUid: { type: String, required: true, unique: true }, // This remains the link to Firebase Auth
  email: { type: String, required: true, unique: true, lowercase: true },
  firstName: { type: String },
  lastName: { type: String },
  address: { type: String },
  phone: { type: String },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('User', UserSchema);